name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 mypy

      - name: Lint & Type Check
        run: |
          flake8 01.App.py monitor.py alert.py
          mypy 01.App.py monitor.py alert.py

      - name: Run Unit Tests
        run: pytest test_app.py

  docker:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t monitoring-app .
